/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/fighters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fighters Endpoint
         * @description Lista fighters paginados, com filtro opcional por nome.
         */
        get: operations["list_fighters_endpoint_api_v1_fighters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fighters/{fighter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fighter Endpoint
         * @description Detalha um fighter pelo id; responde 404 quando não existe.
         */
        get: operations["get_fighter_endpoint_api_v1_fighters__fighter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fighters/{fighter_id}/bouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fighter History Endpoint
         * @description Histórico do lutador em ordem cronológica; responde 404 quando não existe.
         */
        get: operations["get_fighter_history_endpoint_api_v1_fighters__fighter_id__bouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fighters/{fighter_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fighter Stats Endpoint
         * @description Estatísticas resumidas do lutador, computadas on demand; 404 quando não existe.
         */
        get: operations["get_fighter_stats_endpoint_api_v1_fighters__fighter_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events Endpoint
         * @description Lista events paginados, mais recentes primeiro.
         */
        get: operations["list_events_endpoint_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Endpoint
         * @description Detalha um event pelo id com o card de bouts; 404 quando não existe.
         */
        get: operations["get_event_endpoint_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bouts/{bout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bout
         * @description Detalha uma luta com evento e as stats dos dois cantos; 404 se não existe.
         */
        get: operations["get_bout_api_v1_bouts__bout_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/head-to-head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Head To Head
         * @description Confrontos diretos entre dois lutadores em ordem cronológica.
         *
         *     Valida no router: ``a == b`` -> 422 (lutadores devem ser distintos); ``a`` ou
         *     ``b`` inexistente -> 404. Ambos existentes sem confronto direto retorna 200
         *     com lista vazia -- distinto do 404. A leitura sai do selector (router fino).
         */
        get: operations["head_to_head_api_v1_head_to_head_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict/matchup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Predict Matchup Endpoint
         * @description Palpite neutro de canto para o confronto hipotético entre dois lutadores.
         *
         *     ``fighter_a == fighter_b`` -> 422; lutador inexistente -> 404; lutador sem histórico no
         *     granular (existe, mas não tem lutas para derivar features as-of) -> 422; artefato de modelo
         *     ausente -> 503. As probabilidades são neutralizadas de canto (média das duas ordens), então
         *     a ordem dos parâmetros não muda o vencedor previsto.
         */
        get: operations["predict_matchup_endpoint_api_v1_predict_matchup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoutCardFighterOut
         * @description Um participante da luta no card do event: identidade e canto.
         *
         *     Só identidade (id, nome, canto) -- o box-score granular vive no detalhe da
         *     luta. A SPA cruza ``fighter_id`` com ``BoutCardOut.winner_id`` para destacar o
         *     vencedor.
         */
        BoutCardFighterOut: {
            /** Fighter Id */
            fighter_id: number;
            /** Name */
            name: string;
            corner: components["schemas"]["Corner"];
        };
        /**
         * BoutCardOut
         * @description Resumo de uma luta no card do event (sem stats granulares por canto).
         */
        BoutCardOut: {
            /** Id */
            id: number;
            /** Winner Id */
            winner_id: number | null;
            method: components["schemas"]["BoutMethod"];
            /** Round */
            round: number | null;
            /** Ending Time Seconds */
            ending_time_seconds: number | null;
            /** Weight Class */
            weight_class: string | null;
            /** Source */
            source: string;
            /** Fighters */
            fighters: components["schemas"]["BoutCardFighterOut"][];
        };
        /**
         * BoutDetailOut
         * @description Detalhe de uma luta: evento, resultado, contexto, cantos e round-a-round.
         */
        BoutDetailOut: {
            /** Id */
            id: number;
            event: components["schemas"]["BoutEventOut"];
            /** Winner Id */
            winner_id: number | null;
            method: components["schemas"]["BoutMethod"];
            /** Round */
            round: number | null;
            /** Ending Time Seconds */
            ending_time_seconds: number | null;
            /** Weight Class */
            weight_class: string | null;
            /** Title Bout */
            title_bout: boolean | null;
            /** Scheduled Rounds */
            scheduled_rounds: number | null;
            /** Referee */
            referee: string | null;
            /** Source */
            source: string;
            /** Fighters */
            fighters: components["schemas"]["BoutFighterStatsOut"][];
            /** Rounds */
            rounds: components["schemas"]["BoutFighterRoundOut"][];
        };
        /**
         * BoutEventOut
         * @description Evento resumido exposto no detalhe da luta.
         */
        BoutEventOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Location */
            location: string | null;
            /** Source */
            source: string;
        };
        /**
         * BoutFighterRoundOut
         * @description Stats de um lutador num round (uma linha de ``bout_fighter_rounds``).
         *
         *     ``fighter_id`` e ``corner`` identificam o canto dono do round (herdados do
         *     ``bout_fighter``, que é o dono do enum ``corner`` -- a tabela de rounds não o
         *     duplica). ``round`` é o número do round. Todas as stats são granulares por
         *     round e nullable (a Cito preenche o round-a-round só a partir de 2019).
         */
        BoutFighterRoundOut: {
            /** Fighter Id */
            fighter_id: number;
            corner: components["schemas"]["Corner"];
            /** Round */
            round: number;
            /** Knockdowns */
            knockdowns: number | null;
            /** Sig Strikes Landed */
            sig_strikes_landed: number | null;
            /** Sig Strikes Attempted */
            sig_strikes_attempted: number | null;
            /** Takedowns Landed */
            takedowns_landed: number | null;
            /** Takedowns Attempted */
            takedowns_attempted: number | null;
            /** Submission Attempts */
            submission_attempts: number | null;
            /** Control Time Seconds */
            control_time_seconds: number | null;
            /** Total Strikes Landed */
            total_strikes_landed: number | null;
            /** Total Strikes Attempted */
            total_strikes_attempted: number | null;
            /** Head Landed */
            head_landed: number | null;
            /** Head Attempted */
            head_attempted: number | null;
            /** Body Landed */
            body_landed: number | null;
            /** Body Attempted */
            body_attempted: number | null;
            /** Leg Landed */
            leg_landed: number | null;
            /** Leg Attempted */
            leg_attempted: number | null;
            /** Distance Landed */
            distance_landed: number | null;
            /** Distance Attempted */
            distance_attempted: number | null;
            /** Clinch Landed */
            clinch_landed: number | null;
            /** Clinch Attempted */
            clinch_attempted: number | null;
            /** Ground Landed */
            ground_landed: number | null;
            /** Ground Attempted */
            ground_attempted: number | null;
            /** Reversals */
            reversals: number | null;
            /** Source */
            source: string;
        };
        /**
         * BoutFighterStatsOut
         * @description Stats granulares de um lutador numa luta (uma linha de ``bout_fighters``).
         */
        BoutFighterStatsOut: {
            /** Fighter Id */
            fighter_id: number;
            /** Name */
            name: string;
            corner: components["schemas"]["Corner"];
            /** Knockdowns */
            knockdowns: number | null;
            /** Sig Strikes Landed */
            sig_strikes_landed: number | null;
            /** Sig Strikes Attempted */
            sig_strikes_attempted: number | null;
            /** Takedowns Landed */
            takedowns_landed: number | null;
            /** Takedowns Attempted */
            takedowns_attempted: number | null;
            /** Submission Attempts */
            submission_attempts: number | null;
            /** Control Time Seconds */
            control_time_seconds: number | null;
            /** Total Strikes Landed */
            total_strikes_landed: number | null;
            /** Total Strikes Attempted */
            total_strikes_attempted: number | null;
            /** Head Landed */
            head_landed: number | null;
            /** Head Attempted */
            head_attempted: number | null;
            /** Body Landed */
            body_landed: number | null;
            /** Body Attempted */
            body_attempted: number | null;
            /** Leg Landed */
            leg_landed: number | null;
            /** Leg Attempted */
            leg_attempted: number | null;
            /** Distance Landed */
            distance_landed: number | null;
            /** Distance Attempted */
            distance_attempted: number | null;
            /** Clinch Landed */
            clinch_landed: number | null;
            /** Clinch Attempted */
            clinch_attempted: number | null;
            /** Ground Landed */
            ground_landed: number | null;
            /** Ground Attempted */
            ground_attempted: number | null;
            /** Reversals */
            reversals: number | null;
            /** Source */
            source: string;
        };
        /**
         * BoutMethod
         * @description Método de encerramento da luta.
         *
         *     Empate é representado por ``winner_id`` nulo com o ``method`` que o produziu
         *     (tipicamente ``DECISION``); no contest usa ``NO_CONTEST``. Não há valor
         *     ``DRAW`` -- o empate mora na nulabilidade do vencedor, não no método.
         * @enum {string}
         */
        BoutMethod: "ko_tko" | "submission" | "decision" | "dq" | "no_contest";
        /**
         * Corner
         * @description Canto do lutador na luta.
         * @enum {string}
         */
        Corner: "red" | "blue";
        /**
         * EventDetailOut
         * @description Detalhe do event com os bouts do card.
         */
        EventDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Location */
            location: string | null;
            /** Source */
            source: string;
            /** Bouts */
            bouts: components["schemas"]["BoutCardOut"][];
        };
        /**
         * EventOut
         * @description Representação pública de um event.
         */
        EventOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Location */
            location: string | null;
            /** Source */
            source: string;
        };
        /**
         * FighterBoutOut
         * @description Uma luta do histórico do lutador, com as stats daquele lutador naquela luta.
         */
        FighterBoutOut: {
            /** Bout Id */
            bout_id: number;
            /** Event Id */
            event_id: number;
            /** Event Name */
            event_name: string;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            method: components["schemas"]["BoutMethod"];
            /** Round */
            round: number | null;
            /** Ending Time Seconds */
            ending_time_seconds: number | null;
            /** Won */
            won: boolean;
            stats: components["schemas"]["BoutFighterStatsOut"];
            opponent: components["schemas"]["FighterOpponentOut"] | null;
        };
        /**
         * FighterOpponentOut
         * @description Adversário do lutador naquela luta: o outro canto (só identidade).
         */
        FighterOpponentOut: {
            /** Fighter Id */
            fighter_id: number;
            /** Name */
            name: string;
        };
        /**
         * FighterOut
         * @description Representação pública de um lutador.
         */
        FighterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Nickname */
            nickname: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Height Cm */
            height_cm: number | null;
            /** Reach Cm */
            reach_cm: number | null;
            stance: components["schemas"]["Stance"] | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Source */
            source: string;
        };
        /**
         * FighterStatsOut
         * @description Estatísticas resumidas do lutador, computadas on demand (Slice 06).
         *
         *     Não inclui ``source``: RF-09 se aplica a schemas de item; o agregado é
         *     computado e mistura origens (kaggle/cito), não é um registro único (decisão
         *     do plano 003-06). Médias ``None`` quando não há valor a agregar.
         *     ``striking_profile`` traz os shares de golpe por alvo/posição, agregados on
         *     demand a partir dos splits granulares do M5.
         */
        FighterStatsOut: {
            /** Fighter Id */
            fighter_id: number;
            /** Bouts Counted */
            bouts_counted: number;
            /** Avg Sig Strikes Landed */
            avg_sig_strikes_landed: number | null;
            /** Avg Takedowns Landed */
            avg_takedowns_landed: number | null;
            /** Avg Control Time Seconds */
            avg_control_time_seconds: number | null;
            /** Wins By Method */
            wins_by_method: {
                [key: string]: number;
            };
            striking_profile: components["schemas"]["StrikingProfileOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadToHeadOut
         * @description Confrontos diretos entre dois lutadores.
         *
         *     Envelope com os dois ids consultados e a lista de bouts em que ambos
         *     participaram, em ordem cronológica. Cada item reusa ``BoutDetailOut`` (Slice
         *     03): resultado + stats granulares dos dois cantos, nunca médias agregadas.
         */
        HeadToHeadOut: {
            /** Fighter A Id */
            fighter_a_id: number;
            /** Fighter B Id */
            fighter_b_id: number;
            /** Bouts */
            bouts: components["schemas"]["BoutDetailOut"][];
        };
        /**
         * MatchupFighterOut
         * @description Lutador resolvido do banco, exposto no palpite (id + nome).
         */
        MatchupFighterOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * MatchupPredictionOut
         * @description Palpite neutro de canto para um confronto hipotético A vs B.
         *
         *     ``prob_a_wins`` e ``prob_b_wins`` são complementares (somam 1) e já neutralizadas de
         *     canto; ``predicted_winner_id`` é o ``fighter_id`` de maior probabilidade neutra.
         */
        MatchupPredictionOut: {
            fighter_a: components["schemas"]["MatchupFighterOut"];
            fighter_b: components["schemas"]["MatchupFighterOut"];
            /** Prob A Wins */
            prob_a_wins: number;
            /** Prob B Wins */
            prob_b_wins: number;
            /** Predicted Winner Id */
            predicted_winner_id: number;
        };
        /** Page[EventOut] */
        Page_EventOut_: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[FighterOut] */
        Page_FighterOut_: {
            /** Items */
            items: components["schemas"]["FighterOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * Stance
         * @description Base (guarda) do lutador.
         * @enum {string}
         */
        Stance: "orthodox" | "southpaw" | "switch";
        /**
         * StrikingProfileOut
         * @description Perfil de striking agregado on demand: shares de golpe conectado por grupo.
         *
         *     Dois grupos que somam 1 quando definidos: alvo (cabeça/corpo/perna) e posição
         *     (distância/clinch/solo). Cada share é razão de somas na carreira; denominador
         *     zero -> ``None`` (nunca ``inf``/``NaN`` no JSON).
         */
        StrikingProfileOut: {
            /** Share Head */
            share_head: number | null;
            /** Share Body */
            share_body: number | null;
            /** Share Leg */
            share_leg: number | null;
            /** Share Distance */
            share_distance: number | null;
            /** Share Clinch */
            share_clinch: number | null;
            /** Share Ground */
            share_ground: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_fighters_endpoint_api_v1_fighters_get: {
        parameters: {
            query?: {
                name?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FighterOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fighter_endpoint_api_v1_fighters__fighter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fighter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FighterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fighter_history_endpoint_api_v1_fighters__fighter_id__bouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fighter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FighterBoutOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fighter_stats_endpoint_api_v1_fighters__fighter_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fighter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FighterStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_endpoint_api_v1_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_endpoint_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bout_api_v1_bouts__bout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoutDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_api_v1_head_to_head_get: {
        parameters: {
            query: {
                /** @description Id do primeiro lutador */
                a: number;
                /** @description Id do segundo lutador */
                b: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_matchup_endpoint_api_v1_predict_matchup_get: {
        parameters: {
            query: {
                /** @description Id do primeiro lutador */
                fighter_a: number;
                /** @description Id do segundo lutador */
                fighter_b: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupPredictionOut"];
                };
            };
            /** @description Lutador não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Modelo preditivo indisponível: artefato treinado ausente */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
