"""initial schema

Cria as quatro tabelas do domínio (events, fighters, bouts, bout_fighters) e os
tipos enum nativos do Postgres (stance, bout_method, corner). Autogerada via
``alembic revision --autogenerate`` e revisada à mão: a ordem de criação respeita
as FKs (events/fighters antes de bouts; bouts antes de bout_fighters) e o
downgrade dropa explicitamente os tipos enum -- o autogenerate não os remove com
as tabelas, e sem isso sobra resíduo (uma segunda upgrade quebraria por tipo já
existente).

Revision ID: c62506a8b256
Revises:
Create Date: 2026-07-10 15:10:37.616175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62506a8b256'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'date', name='uq_event_name_date')
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('reach_cm', sa.Integer(), nullable=True),
    sa.Column('stance', sa.Enum('orthodox', 'southpaw', 'switch', name='stance'), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighters_name_normalized'), 'fighters', ['name_normalized'], unique=False)
    op.create_table('bouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('ko_tko', 'submission', 'decision', 'dq', 'no_contest', name='bout_method'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('ending_time_seconds', sa.Integer(), nullable=True),
    sa.Column('weight_class', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bout_fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bout_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('corner', sa.Enum('red', 'blue', name='corner'), nullable=False),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submission_attempts', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['bout_id'], ['bouts.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bout_id', 'fighter_id', name='uq_bout_fighter')
    )
    op.create_index(op.f('ix_bout_fighters_fighter_id'), 'bout_fighters', ['fighter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bout_fighters_fighter_id'), table_name='bout_fighters')
    op.drop_table('bout_fighters')
    op.drop_table('bouts')
    op.drop_index(op.f('ix_fighters_name_normalized'), table_name='fighters')
    op.drop_table('fighters')
    op.drop_table('events')
    # ### end Alembic commands ###
    # Os tipos enum não são removidos junto com as tabelas -- dropar explicitamente
    # para não deixar resíduo (CA-02) e permitir uma nova upgrade limpa.
    bind = op.get_bind()
    sa.Enum(name='corner').drop(bind, checkfirst=True)
    sa.Enum(name='bout_method').drop(bind, checkfirst=True)
    sa.Enum(name='stance').drop(bind, checkfirst=True)
