"""m5: splits, contexto e bout_fighter_rounds

Enriquecimento granular do M5 (SPEC M5, Slice 01 -- ADR 0004). Migration
**aditiva** e reversível, aplicada numa única fundação **antes** de qualquer
backfill (o dado vem nas Slices 02+):

- ``bout_fighters`` ganha as 15 colunas wide de split (total/head/body/leg,
  distância/clinch/solo landed+attempted, reversals) -- atributo 1:1 do canto,
  todas nullable.
- ``bouts`` ganha contexto de luta nullable (``title_bout``, ``scheduled_rounds``,
  ``referee``).
- ``fighters`` ganha ``weight_kg`` (float, atributo físico estático) nullable.
- Tabela nova ``bout_fighter_rounds``: conjunto completo de stats por canto POR
  ROUND (7 base + 15 splits), FK indexada ``bout_fighter_id -> bout_fighters.id``,
  ``UNIQUE(bout_fighter_id, round)`` e ``source`` NOT NULL.

Autogerada via ``alembic revision --autogenerate`` e **revisada à mão**. Nenhuma
coluna/tabela pré-existente é alterada de forma destrutiva; o ``downgrade`` é
simétrico (dropa só o próprio artefato aditivo). **Não** toca o enum ``corner``:
``bout_fighter_rounds`` não tem canto (herda de ``bout_fighter_id``), então não há
referência/criação/drop do tipo ``corner`` (dono: ``c62506a8b256``) -- evita a
armadilha "type corner already exists".

Revision ID: ff6591f2d146
Revises: f3d1bfc5aa70
Create Date: 2026-07-13 15:47:13.578847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6591f2d146'
down_revision: Union[str, Sequence[str], None] = 'f3d1bfc5aa70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bout_fighter_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bout_fighter_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submission_attempts', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('total_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('head_landed', sa.Integer(), nullable=True),
    sa.Column('head_attempted', sa.Integer(), nullable=True),
    sa.Column('body_landed', sa.Integer(), nullable=True),
    sa.Column('body_attempted', sa.Integer(), nullable=True),
    sa.Column('leg_landed', sa.Integer(), nullable=True),
    sa.Column('leg_attempted', sa.Integer(), nullable=True),
    sa.Column('distance_landed', sa.Integer(), nullable=True),
    sa.Column('distance_attempted', sa.Integer(), nullable=True),
    sa.Column('clinch_landed', sa.Integer(), nullable=True),
    sa.Column('clinch_attempted', sa.Integer(), nullable=True),
    sa.Column('ground_landed', sa.Integer(), nullable=True),
    sa.Column('ground_attempted', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['bout_fighter_id'], ['bout_fighters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bout_fighter_id', 'round', name='uq_bout_fighter_round')
    )
    op.create_index(op.f('ix_bout_fighter_rounds_bout_fighter_id'), 'bout_fighter_rounds', ['bout_fighter_id'], unique=False)
    op.add_column('bout_fighters', sa.Column('total_strikes_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('total_strikes_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('head_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('head_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('body_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('body_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('leg_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('leg_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('distance_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('distance_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('clinch_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('clinch_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('ground_landed', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('ground_attempted', sa.Integer(), nullable=True))
    op.add_column('bout_fighters', sa.Column('reversals', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('title_bout', sa.Boolean(), nullable=True))
    op.add_column('bouts', sa.Column('scheduled_rounds', sa.Integer(), nullable=True))
    op.add_column('bouts', sa.Column('referee', sa.String(length=128), nullable=True))
    op.add_column('fighters', sa.Column('weight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fighters', 'weight_kg')
    op.drop_column('bouts', 'referee')
    op.drop_column('bouts', 'scheduled_rounds')
    op.drop_column('bouts', 'title_bout')
    op.drop_column('bout_fighters', 'reversals')
    op.drop_column('bout_fighters', 'ground_attempted')
    op.drop_column('bout_fighters', 'ground_landed')
    op.drop_column('bout_fighters', 'clinch_attempted')
    op.drop_column('bout_fighters', 'clinch_landed')
    op.drop_column('bout_fighters', 'distance_attempted')
    op.drop_column('bout_fighters', 'distance_landed')
    op.drop_column('bout_fighters', 'leg_attempted')
    op.drop_column('bout_fighters', 'leg_landed')
    op.drop_column('bout_fighters', 'body_attempted')
    op.drop_column('bout_fighters', 'body_landed')
    op.drop_column('bout_fighters', 'head_attempted')
    op.drop_column('bout_fighters', 'head_landed')
    op.drop_column('bout_fighters', 'total_strikes_attempted')
    op.drop_column('bout_fighters', 'total_strikes_landed')
    op.drop_index(op.f('ix_bout_fighter_rounds_bout_fighter_id'), table_name='bout_fighter_rounds')
    op.drop_table('bout_fighter_rounds')
    # ### end Alembic commands ###
